server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ackss;encrypt=true;trustServerCertificate=true
    username: springuser
    password: NewSecurePassword!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
